name: Build and Deploy GitHub Package

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.2.2
        name: Install pnpm
        with:
          version: latest

      - uses: actions/setup-node@v2

      - run: pnpm install

      - uses: actions/setup-node@v2
        with:
          node-version: "18.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@codevachon"

      - run: pnpm run build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.CODEVACHON_GITHUB_TOKEN }}
